/**
 * Localized Bible book names keyed by translation ID → book ID.
 * Falls back to the English name from BIBLE_BOOKS when a key is absent.
 */

type BookNameMap = Record<string, string>;

const BOOK_NAMES_BY_TRANSLATION: Record<string, BookNameMap> = {

  // ── French (LSG) ────────────────────────────────────────────────────
  lsg: {
    GEN: 'Genèse',         EXO: 'Exode',           LEV: 'Lévitique',
    NUM: 'Nombres',         DEU: 'Deutéronome',     JOS: 'Josué',
    JDG: 'Juges',           RUT: 'Ruth',             '1SA': '1 Samuel',
    '2SA': '2 Samuel',      '1KI': '1 Rois',         '2KI': '2 Rois',
    '1CH': '1 Chroniques',  '2CH': '2 Chroniques',  EZR: 'Esdras',
    NEH: 'Néhémie',         EST: 'Esther',           JOB: 'Job',
    PSA: 'Psaumes',         PRO: 'Proverbes',        ECC: 'Ecclésiaste',
    SNG: 'Cantique des Cantiques', ISA: 'Ésaïe',    JER: 'Jérémie',
    LAM: 'Lamentations',    EZK: 'Ézéchiel',         DAN: 'Daniel',
    HOS: 'Osée',            JOL: 'Joël',             AMO: 'Amos',
    OBD: 'Abdias',          JON: 'Jonas',            MIC: 'Michée',
    NAM: 'Nahum',           HAB: 'Habacuc',          ZEP: 'Sophonie',
    HAG: 'Aggée',           ZEC: 'Zacharie',         MAL: 'Malachie',
    MAT: 'Matthieu',        MRK: 'Marc',             LUK: 'Luc',
    JHN: 'Jean',            ACT: 'Actes',            ROM: 'Romains',
    '1CO': '1 Corinthiens', '2CO': '2 Corinthiens', GAL: 'Galates',
    EPH: 'Éphésiens',       PHP: 'Philippiens',      COL: 'Colossiens',
    '1TH': '1 Thessaloniciens', '2TH': '2 Thessaloniciens',
    '1TI': '1 Timothée',    '2TI': '2 Timothée',    TIT: 'Tite',
    PHM: 'Philémon',        HEB: 'Hébreux',          JAS: 'Jacques',
    '1PE': '1 Pierre',      '2PE': '2 Pierre',       '1JN': '1 Jean',
    '2JN': '2 Jean',        '3JN': '3 Jean',         JUD: 'Jude',
    REV: 'Apocalypse',
  },

  // ── Yoruba (YOR) — Bibeli Mimo ─────────────────────────────────────
  yor: {
    GEN: 'Genesisi',        EXO: 'Eksodu',           LEV: 'Lefitiku',
    NUM: 'Numeri',          DEU: 'Deuteronomi',      JOS: 'Joṣua',
    JDG: 'Adajọ',          RUT: 'Rutu',             '1SA': '1 Samueli',
    '2SA': '2 Samueli',     '1KI': '1 Awọn Ọba',    '2KI': '2 Awọn Ọba',
    '1CH': '1 Kronika',     '2CH': '2 Kronika',      EZR: 'Esira',
    NEH: 'Nehemiah',        EST: 'Esteri',           JOB: 'Jobu',
    PSA: 'Orin Dafidi',     PRO: 'Owe',              ECC: 'Oniwasu',
    SNG: 'Orin Solomoni',   ISA: 'Isaia',            JER: 'Jeremia',
    LAM: 'Arọ',             EZK: 'Esekiẹli',         DAN: 'Daniẹli',
    HOS: 'Hoseà',           JOL: 'Joẹli',            AMO: 'Amosi',
    OBD: 'Obadiah',         JON: 'Jona',             MIC: 'Mika',
    NAM: 'Nahumu',          HAB: 'Habakkuku',        ZEP: 'Sefaniah',
    HAG: 'Hagayi',          ZEC: 'Sekariah',         MAL: 'Malaki',
    MAT: 'Matius',          MRK: 'Marku',            LUK: 'Luku',
    JHN: 'Johanu',          ACT: 'Iṣẹ Aposteli',    ROM: 'Romu',
    '1CO': '1 Korinti',     '2CO': '2 Korinti',      GAL: 'Galatia',
    EPH: 'Efesu',           PHP: 'Filipi',           COL: 'Kolosse',
    '1TH': '1 Tesalonika',  '2TH': '2 Tesalonika',
    '1TI': '1 Timoteu',     '2TI': '2 Timoteu',     TIT: 'Titu',
    PHM: 'Filemoni',        HEB: 'Ebrania',          JAS: 'Jakobuu',
    '1PE': '1 Peteru',      '2PE': '2 Peteru',       '1JN': '1 Johanu',
    '2JN': '2 Johanu',      '3JN': '3 Johanu',       JUD: 'Judasi',
    REV: 'Ifihan',
  },

  // ── Igbo (IBO) — Biblia Nso ────────────────────────────────────────
  ibo: {
    GEN: 'Jenesis',         EXO: 'Ọpụpụ',           LEV: 'Livitikus',
    NUM: 'Ọnụọgụ',          DEU: 'Deuterọnọmi',      JOS: 'Joshụa',
    JDG: 'Ndị Ọkpụkpọ',    RUT: 'Rut',              '1SA': '1 Samụel',
    '2SA': '2 Samụel',      '1KI': '1 Ọchịchị',      '2KI': '2 Ọchịchị',
    '1CH': '1 Ihe Ndekọọ',  '2CH': '2 Ihe Ndekọọ',  EZR: 'Ezra',
    NEH: 'Nehemaịa',        EST: 'Esta',             JOB: 'Jiọb',
    PSA: 'Abu Ọma',         PRO: 'Ilu',              ECC: 'Onye Nkuzi',
    SNG: 'Abu Abụ Sọlọmọn', ISA: 'Aịzaịa',          JER: 'Jeremaia',
    LAM: 'Akwa Ákwá',       EZK: 'Ezekiel',          DAN: 'Daniẹl',
    HOS: 'Hoseà',           JOL: 'Joẹl',             AMO: 'Amos',
    OBD: 'Obaịdaịa',        JON: 'Jona',             MIC: 'Maịka',
    NAM: 'Nahum',           HAB: 'Habakkuk',         ZEP: 'Zefanaịa',
    HAG: 'Hagaị',           ZEC: 'Zekaria',          MAL: 'Malaki',
    MAT: 'Matiu',           MRK: 'Mak',              LUK: 'Luk',
    JHN: 'Jọn',             ACT: 'Ọrụ Ndị Ozi',      ROM: 'Rom',
    '1CO': '1 Kọrint',      '2CO': '2 Kọrint',       GAL: 'Gal',
    EPH: 'Efes',            PHP: 'Filipaị',          COL: 'Kọlos',
    '1TH': '1 Tesalọnaịka', '2TH': '2 Tesalọnaịka',
    '1TI': '1 Timọti',      '2TI': '2 Timọti',       TIT: 'Taịtọs',
    PHM: 'Filimọn',         HEB: 'Hib',              JAS: 'Jems',
    '1PE': '1 Pita',        '2PE': '2 Pita',         '1JN': '1 Jọn',
    '2JN': '2 Jọn',         '3JN': '3 Jọn',          JUD: 'Jud',
    REV: 'Mkpụghachi',
  },

  // ── Hausa (HAU) — Littafi Mai Tsarki ───────────────────────────────
  hau: {
    GEN: 'Farawa',          EXO: 'Fitowa',           LEV: 'Firistoci',
    NUM: 'Ƙidaya',          DEU: "Shari'a Ta Biyu",  JOS: 'Yoshuwa',
    JDG: 'Alƙalai',         RUT: 'Rut',              '1SA': "1 Sama'ila",
    "2SA": "2 Sama'ila",    '1KI': '1 Sarakuna',     '2KI': '2 Sarakuna',
    '1CH': '1 Tarihi',      '2CH': '2 Tarihi',       EZR: 'Ezra',
    NEH: 'Nehemiya',        EST: 'Esther',           JOB: 'Ayuba',
    PSA: 'Zabura',          PRO: 'Karin Magana',     ECC: 'Mai Bincike',
    SNG: 'Waƙar Waƙoƙi',   ISA: 'Ishaya',           JER: 'Irmiya',
    LAM: 'Makoki',          EZK: 'Ezekyel',          DAN: 'Daniyel',
    HOS: 'Hoshea',          JOL: 'Yowel',            AMO: 'Amos',
    OBD: 'Obadiyah',        JON: 'Yunana',           MIC: 'Mika',
    NAM: 'Nahum',           HAB: 'Habakkuk',         ZEP: 'Zefaniya',
    HAG: 'Hagai',           ZEC: 'Zekariya',         MAL: 'Malaki',
    MAT: 'Matta',           MRK: 'Markus',           LUK: 'Luka',
    JHN: 'Yohanna',         ACT: 'Ayyukan Manzanni', ROM: 'Romawa',
    '1CO': '1 Korantiyawa', '2CO': '2 Korantiyawa',  GAL: 'Galatiyawa',
    EPH: 'Afisiyawa',       PHP: 'Filificiyawa',     COL: 'Kolossiyawa',
    '1TH': '1 Tessaloniyawa', '2TH': '2 Tessaloniyawa',
    '1TI': '1 Timoti',      '2TI': '2 Timoti',       TIT: 'Tito',
    PHM: 'Filemon',         HEB: 'Ibraniyawa',       JAS: 'Yakubu',
    '1PE': '1 Bitrus',      '2PE': '2 Bitrus',       '1JN': '1 Yohanna',
    '2JN': '2 Yohanna',     '3JN': '3 Yohanna',      JUD: 'Yahuda',
    REV: "Ruy'ar Yohanna",
  },

  // ── Twi / Akan Asante (TWI) — Twere Kronkron ───────────────────────
  twi: {
    GEN: 'Adiyisɛm',        EXO: 'Otufuo',           LEV: 'Afahye Nhyehyɛemu',
    NUM: 'Nɔma',            DEU: 'Mmara a Ɛtoɔ So Mmienu', JOS: 'Yosu',
    JDG: 'Atemmu',          RUT: 'Rut',              '1SA': '1 Samuɛl',
    '2SA': '2 Samuɛl',      '1KI': '1 Ahemfo',       '2KI': '2 Ahemfo',
    '1CH': '1 Kronekron Asɛm', '2CH': '2 Kronekron Asɛm', EZR: 'Esra',
    NEH: 'Nehemia',         EST: 'Esther',           JOB: 'Hiob',
    PSA: 'Ndwom',           PRO: 'Nnwonkoro',        ECC: 'Ɔkyerɛkyerɛni',
    SNG: 'Ayeyi Ndwom',     ISA: 'Yesaia',           JER: 'Yeremia',
    LAM: 'Awerɛhow',        EZK: 'Hesekiel',         DAN: 'Daniel',
    HOS: 'Hosea',           JOL: 'Yoel',             AMO: 'Amos',
    OBD: 'Obadiah',         JON: 'Yona',             MIC: 'Mika',
    NAM: 'Nahum',           HAB: 'Habakkuk',         ZEP: 'Sefanias',
    HAG: 'Hagai',           ZEC: 'Sakaria',          MAL: 'Malaki',
    MAT: 'Matius',          MRK: 'Marku',            LUK: 'Luka',
    JHN: 'Yohane',          ACT: 'Asɔmduafɔ Nnwuma', ROM: 'Romafo',
    '1CO': '1 Korinto',     '2CO': '2 Korinto',      GAL: 'Galatia',
    EPH: 'Efeso',           PHP: 'Filipi',           COL: 'Kolase',
    '1TH': '1 Tesalonika',  '2TH': '2 Tesalonika',
    '1TI': '1 Timoteo',     '2TI': '2 Timoteo',      TIT: 'Tito',
    PHM: 'Filemon',         HEB: 'Hebreofo',         JAS: 'Yakobo',
    '1PE': '1 Petro',       '2PE': '2 Petro',        '1JN': '1 Yohane',
    '2JN': '2 Yohane',      '3JN': '3 Yohane',       JUD: 'Yuda',
    REV: 'Nsɛnkyerɛnne',
  },

  // ── Nigerian Pidgin (PCM) — Naija Pidgin Baibul ─────────────────────
  pcm: {
    GEN: 'Genesis',         EXO: 'Exodus',           LEV: 'Leviticus',
    NUM: 'Numbers',         DEU: 'Deuteronomy',      JOS: 'Joshua',
    JDG: 'Judges',          RUT: 'Ruth',             '1SA': '1 Samuel',
    '2SA': '2 Samuel',      '1KI': '1 Kings',        '2KI': '2 Kings',
    '1CH': '1 Chronicles',  '2CH': '2 Chronicles',  EZR: 'Ezra',
    NEH: 'Nehemiah',        EST: 'Esther',           JOB: 'Job',
    PSA: 'Psalms',          PRO: 'Proverbs',         ECC: 'Ecclesiastes',
    SNG: 'Song of Solomon', ISA: 'Isaiah',           JER: 'Jeremiah',
    LAM: 'Lamentations',    EZK: 'Ezekiel',          DAN: 'Daniel',
    HOS: 'Hosea',           JOL: 'Joel',             AMO: 'Amos',
    OBD: 'Obadiah',         JON: 'Jonah',            MIC: 'Micah',
    NAM: 'Nahum',           HAB: 'Habakkuk',         ZEP: 'Zephaniah',
    HAG: 'Haggai',          ZEC: 'Zechariah',        MAL: 'Malachi',
    MAT: 'Matthew',         MRK: 'Mark',             LUK: 'Luke',
    JHN: 'John',            ACT: 'Acts',             ROM: 'Romans',
    '1CO': '1 Corinthians', '2CO': '2 Corinthians',  GAL: 'Galatians',
    EPH: 'Ephesians',       PHP: 'Philippians',      COL: 'Colossians',
    '1TH': '1 Thessalonians', '2TH': '2 Thessalonians',
    '1TI': '1 Timothy',     '2TI': '2 Timothy',      TIT: 'Titus',
    PHM: 'Philemon',        HEB: 'Hebrews',          JAS: 'James',
    '1PE': '1 Peter',       '2PE': '2 Peter',        '1JN': '1 John',
    '2JN': '2 John',        '3JN': '3 John',         JUD: 'Jude',
    REV: 'Revelation',
  },

  // ── Afrikaans (AFR) — Ou Vertaling ─────────────────────────────────
  afr: {
    GEN: 'Genesis',         EXO: 'Eksodus',          LEV: 'Levitikus',
    NUM: 'Numeri',          DEU: 'Deuteronomium',    JOS: 'Josua',
    JDG: 'Rigters',         RUT: 'Rut',              '1SA': '1 Samuel',
    '2SA': '2 Samuel',      '1KI': '1 Konings',      '2KI': '2 Konings',
    '1CH': '1 Kronieke',    '2CH': '2 Kronieke',     EZR: 'Esra',
    NEH: 'Nehemia',         EST: 'Ester',            JOB: 'Job',
    PSA: 'Psalms',          PRO: 'Spreuke',          ECC: 'Prediker',
    SNG: 'Hooglied',        ISA: 'Jesaja',           JER: 'Jeremia',
    LAM: 'Klaagliedere',    EZK: 'Esegiël',          DAN: 'Daniël',
    HOS: 'Hosea',           JOL: 'Joël',             AMO: 'Amos',
    OBD: 'Obadja',          JON: 'Jona',             MIC: 'Miga',
    NAM: 'Nahum',           HAB: 'Habakuk',          ZEP: 'Sefanja',
    HAG: 'Haggai',          ZEC: 'Sagaria',          MAL: 'Maleagi',
    MAT: 'Matteus',         MRK: 'Markus',           LUK: 'Lukas',
    JHN: 'Johannes',        ACT: 'Handelinge',       ROM: 'Romeine',
    '1CO': '1 Korintiërs',  '2CO': '2 Korintiërs',  GAL: 'Galasiërs',
    EPH: 'Efésiërs',        PHP: 'Filippense',       COL: 'Kolossense',
    '1TH': '1 Tessalonisense', '2TH': '2 Tessalonisense',
    '1TI': '1 Timoteus',    '2TI': '2 Timoteus',     TIT: 'Titus',
    PHM: 'Filemon',         HEB: 'Hebreërs',         JAS: 'Jakobus',
    '1PE': '1 Petrus',      '2PE': '2 Petrus',       '1JN': '1 Johannes',
    '2JN': '2 Johannes',    '3JN': '3 Johannes',     JUD: 'Judas',
    REV: 'Openbaring',
  },

  // ── Amharic (AMH) — መጽሐፍ ቅዱስ ────────────────────────────────────
  amh: {
    GEN: 'ዘፍጥረት',          EXO: 'ዘጸአት',            LEV: 'ዘሌዋውያን',
    NUM: 'ዘኍልቍ',           DEU: 'ዘዳግም',            JOS: 'ኢያሱ',
    JDG: 'መሳፍንት',          RUT: 'ሩት',              '1SA': '1 ሳሙኤል',
    '2SA': '2 ሳሙኤል',       '1KI': '1 ነገሥት',        '2KI': '2 ነገሥት',
    '1CH': '1 ዜና መዋዕል',    '2CH': '2 ዜና መዋዕል',    EZR: 'ዕዝራ',
    NEH: 'ነህምያ',            EST: 'አስቴር',            JOB: 'ኢዮብ',
    PSA: 'መዝሙር',           PRO: 'ምሳሌ',             ECC: 'መክብብ',
    SNG: 'መኃልየ መኃልይ',     ISA: 'ኢሳይያስ',          JER: 'ኤርምያስ',
    LAM: 'ሰቆቃወ ኤርምያስ',    EZK: 'ሕዝቅኤል',          DAN: 'ዳንኤል',
    HOS: 'ሆሴዕ',            JOL: 'ኢዮኤል',           AMO: 'አሞጽ',
    OBD: 'አብድዩ',           JON: 'ዮናስ',             MIC: 'ሚክያስ',
    NAM: 'ናሆም',            HAB: 'ዕንባቆም',           ZEP: 'ሶፎንያስ',
    HAG: 'ሐጌ',             ZEC: 'ዘካርያስ',           MAL: 'ሚልክያስ',
    MAT: 'ማቴዎስ',           MRK: 'ማርቆስ',           LUK: 'ሉቃስ',
    JHN: 'ዮሐንስ',           ACT: 'የሐዋርያት ሥራ',     ROM: 'ሮሜ',
    '1CO': '1 ቆሮንቶስ',      '2CO': '2 ቆሮንቶስ',      GAL: 'ገላትያ',
    EPH: 'ኤፌሶን',           PHP: 'ፊልጵስዩስ',         COL: 'ቈሎሴ',
    '1TH': '1 ተሰሎንቄ',      '2TH': '2 ተሰሎንቄ',
    '1TI': '1 ጢሞቴዎስ',      '2TI': '2 ጢሞቴዎስ',      TIT: 'ቲቶ',
    PHM: 'ፊልሞና',           HEB: 'ዕብራይስጥ',         JAS: 'ያዕቆብ',
    '1PE': '1 ጴጥሮስ',       '2PE': '2 ጴጥሮስ',       '1JN': '1 ዮሐንስ',
    '2JN': '2 ዮሐንስ',       '3JN': '3 ዮሐንስ',        JUD: 'ይሁዳ',
    REV: 'ራዕይ',
  },

  // ── Swahili (SWA) — Biblia Takatifu ────────────────────────────────
  swa: {
    GEN: 'Mwanzo',          EXO: 'Kutoka',           LEV: 'Mambo ya Walawi',
    NUM: 'Hesabu',          DEU: 'Kumbukumbu la Torati', JOS: 'Yoshua',
    JDG: 'Waamuzi',         RUT: 'Ruthu',            '1SA': '1 Samweli',
    '2SA': '2 Samweli',     '1KI': '1 Wafalme',      '2KI': '2 Wafalme',
    '1CH': '1 Mambo ya Nyakati', '2CH': '2 Mambo ya Nyakati', EZR: 'Ezra',
    NEH: 'Nehemia',         EST: 'Esta',             JOB: 'Ayubu',
    PSA: 'Zaburi',          PRO: 'Mithali',          ECC: 'Mhubiri',
    SNG: 'Wimbo Ulio Bora', ISA: 'Isaya',            JER: 'Yeremia',
    LAM: 'Maombolezo',      EZK: 'Ezekieli',         DAN: 'Danieli',
    HOS: 'Hosea',           JOL: 'Yoeli',            AMO: 'Amosi',
    OBD: 'Obadia',          JON: 'Yona',             MIC: 'Mika',
    NAM: 'Nahumu',          HAB: 'Habakuki',         ZEP: 'Sefania',
    HAG: 'Hagai',           ZEC: 'Zekaria',          MAL: 'Malaki',
    MAT: 'Mathayo',         MRK: 'Marko',            LUK: 'Luka',
    JHN: 'Yohana',          ACT: 'Matendo ya Mitume', ROM: 'Warumi',
    '1CO': '1 Wakorintho',  '2CO': '2 Wakorintho',   GAL: 'Wagalatia',
    EPH: 'Waefeso',         PHP: 'Wafilipi',         COL: 'Wakolosai',
    '1TH': '1 Wathesalonike', '2TH': '2 Wathesalonike',
    '1TI': '1 Timotheo',    '2TI': '2 Timotheo',     TIT: 'Tito',
    PHM: 'Filemoni',        HEB: 'Waebrania',        JAS: 'Yakobo',
    '1PE': '1 Petro',       '2PE': '2 Petro',        '1JN': '1 Yohana',
    '2JN': '2 Yohana',      '3JN': '3 Yohana',       JUD: 'Yuda',
    REV: 'Ufunuo',
  },

  // ── Shona (SNA) — Bhaibheri ────────────────────────────────────────
  sna: {
    GEN: 'Genesi',          EXO: 'Eksodo',           LEV: 'Revhitiko',
    NUM: 'Numeri',          DEU: 'Duteronomi',       JOS: 'Joshua',
    JDG: 'Vatongi',         RUT: 'Rute',             '1SA': '1 Samueri',
    '2SA': '2 Samueri',     '1KI': '1 Madzimambo',   '2KI': '2 Madzimambo',
    '1CH': '1 Makoronike',  '2CH': '2 Makoronike',   EZR: 'Ezra',
    NEH: 'Nehemiya',        EST: 'Esteri',           JOB: 'Job',
    PSA: 'Mapisarema',      PRO: 'Zvirevo',          ECC: 'Muparidzi',
    SNG: 'Rwiyo rwoMuridzi', ISA: 'Isaya',           JER: 'Jeremiya',
    LAM: 'Mariro',          EZK: 'Ezekieri',         DAN: 'Dhanieri',
    HOS: 'Hosea',           JOL: 'Joeri',            AMO: 'Amosi',
    OBD: 'Obhadiya',        JON: 'Jona',             MIC: 'Mika',
    NAM: 'Nahumu',          HAB: 'Habahuku',         ZEP: 'Zefaniya',
    HAG: 'Hagai',           ZEC: 'Zekaria',          MAL: 'Maraki',
    MAT: 'Mateu',           MRK: 'Mako',             LUK: 'Ruka',
    JHN: 'Johane',          ACT: 'Mabasa',           ROM: 'VaRoma',
    '1CO': '1 VaKorinde',   '2CO': '2 VaKorinde',    GAL: 'VaGaratiya',
    EPH: 'VaEfeso',         PHP: 'VaFiripi',         COL: 'VaKorose',
    '1TH': '1 VaTesaronika', '2TH': '2 VaTesaronika',
    '1TI': '1 Timoti',      '2TI': '2 Timoti',       TIT: 'Tito',
    PHM: 'Firemoni',        HEB: 'VaHeberu',         JAS: 'Jakobho',
    '1PE': '1 Petro',       '2PE': '2 Petro',        '1JN': '1 Johane',
    '2JN': '2 Johane',      '3JN': '3 Johane',       JUD: 'Judhasi',
    REV: 'Zvakazarurwa',
  },

  // ── Ndebele / isiNdebele (NDE) — IBhayibhili ───────────────────────
  nde: {
    GEN: 'UGenesisi',       EXO: 'U-Eksodusi',       LEV: 'ULevitikusi',
    NUM: 'AmaNumeri',       DEU: 'UDuteronomi',      JOS: 'UJoshuwa',
    JDG: 'AbaHluleli',      RUT: 'URuthe',           '1SA': '1 USamuyeli',
    '2SA': '2 USamuyeli',   '1KI': '1 AmaKhosi',     '2KI': '2 AmaKhosi',
    '1CH': '1 IziKronike',  '2CH': '2 IziKronike',   EZR: 'UEzra',
    NEH: 'UNehemiya',       EST: 'U-Esteri',         JOB: 'UJobe',
    PSA: 'AmaHubo',         PRO: 'IzAga',            ECC: 'UMtshumayeli',
    SNG: 'INgoma YezIngoma', ISA: 'U-Isaya',         JER: 'UJeremiya',
    LAM: 'IziLilo',         EZK: 'UHezekeli',        DAN: 'UDaniyeli',
    HOS: 'UHosea',          JOL: 'UJoweli',          AMO: 'U-Amosi',
    OBD: 'U-Obadiya',       JON: 'UJona',            MIC: 'UMika',
    NAM: 'UNahumu',         HAB: 'UHabakhuki',       ZEP: 'UZefaniya',
    HAG: 'UHagayi',         ZEC: 'UZekariya',        MAL: 'UMalaki',
    MAT: 'UMathewu',        MRK: 'UMarko',           LUK: 'ULuka',
    JHN: 'UJohane',         ACT: 'IzEnzo',           ROM: 'AmaRoma',
    '1CO': '1 AmaKorinte',  '2CO': '2 AmaKorinte',   GAL: 'AmaGalathiya',
    EPH: 'AmaEfesu',        PHP: 'AmaFiliphi',       COL: 'AmaKolose',
    '1TH': '1 AmaThesalonika', '2TH': '2 AmaThesalonika',
    '1TI': '1 UThimothewu', '2TI': '2 UThimothewu',  TIT: 'UTitosi',
    PHM: 'UFilemoni',       HEB: 'AmaHeberu',        JAS: 'UJakobe',
    '1PE': '1 UPetru',      '2PE': '2 UPetru',       '1JN': '1 UJohane',
    '2JN': '2 UJohane',     '3JN': '3 UJohane',      JUD: 'UJuda',
    REV: 'IsAmbulo',
  },

  // ── Ewe (EWE) — Bibla ──────────────────────────────────────────────
  ewe: {
    GEN: 'Dziɖoɖowo',       EXO: 'Exodo',            LEV: 'Levitiku',
    NUM: 'Nomadzewo',        DEU: 'Deuteronomi',      JOS: 'Yosua',
    JDG: 'Adanulawo',        RUT: 'Ruta',             '1SA': '1 Samuel',
    '2SA': '2 Samuel',       '1KI': '1 Fiaawo',       '2KI': '2 Fiaawo',
    '1CH': '1 Kronike',      '2CH': '2 Kronike',      EZR: 'Ezra',
    NEH: 'Nehemia',          EST: 'Esther',           JOB: 'Job',
    PSA: 'Habone',           PRO: 'Nuyowo',           ECC: 'Dze Nugbɔgbɔ La',
    SNG: 'Habone si Dze Ŋutɔ', ISA: 'Isaia',         JER: 'Jeremia',
    LAM: 'Kpekpleli',        EZK: 'Ezekiel',          DAN: 'Daniyel',
    HOS: 'Hosea',            JOL: 'Joel',             AMO: 'Amos',
    OBD: 'Obadiya',          JON: 'Jona',             MIC: 'Mika',
    NAM: 'Nahum',            HAB: 'Habakuku',         ZEP: 'Sefaniya',
    HAG: 'Hagayi',           ZEC: 'Zekariya',         MAL: 'Malaki',
    MAT: 'Matio',            MRK: 'Marku',            LUK: 'Luka',
    JHN: 'Yoane',            ACT: 'Apostoloawo Dɔwɔwɔ', ROM: 'Roma',
    '1CO': '1 Korinto',      '2CO': '2 Korinto',      GAL: 'Galatia',
    EPH: 'Efeso',            PHP: 'Filipi',           COL: 'Kolose',
    '1TH': '1 Tesalonika',   '2TH': '2 Tesalonika',
    '1TI': '1 Timoteo',      '2TI': '2 Timoteo',      TIT: 'Tito',
    PHM: 'Filemone',         HEB: 'Hebru',            JAS: 'Yakobu',
    '1PE': '1 Petro',        '2PE': '2 Petro',        '1JN': '1 Yoane',
    '2JN': '2 Yoane',        '3JN': '3 Yoane',        JUD: 'Yuda',
    REV: 'Yoane Sɛnkekeli',
  },
};

/**
 * Returns the localized book name for the given translation.
 * Falls back to `englishName` if no localization exists.
 */
export function getLocalizedBookName(
  bookId: string,
  translationId: string,
  englishName: string,
): string {
  return BOOK_NAMES_BY_TRANSLATION[translationId]?.[bookId] ?? englishName;
}
